using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Block : MonoBehaviour {
	[SerializeField] AudioClip breakSound;
	[SerializeField] GameObject blockSparklesVFX;
	[SerializeField] int maxHits;
	[SerializeField] Sprite[] hitSprites;

	Level level;
	
	[SerializeField] int timesHit;

	private void Start()
	{
		CountBreakableBlocks();
	}

	private void CountBreakableBlocks()
	{
		level = FindObjectOfType<Level>();
		if (tag == "Breakable")
		{
			level.CountBreakableBlocks();
		}

	}

	private void OnCollisionEnter2D(Collision2D collision)
	{
		HandleHit();
	}

	private void HandleHit()
	{
		timesHit++;
		if (timesHit >= maxHits)
		{
			DestroyBlock();
		}
		else
		{
			ShowNextHitSprite();
		}
	}

	private void ShowNextHitSprite()
	{
		int spriteIndex = timesHit - 1;
		GetComponent<SpriteRenderer>().sprite = hitSprites[spriteIndex];
	}

	private void DestroyBlock()
	{	
		PlayBlockDestroySFX();
		Destroy(gameObject);
		level.BlockDestroyed();
		TriggerSparklesVFX();
	}

	private void PlayBlockDestroySFX()
	{
		FindObjectOfType<GameStatus>().AddToScore();
		AudioSource.PlayClipAtPoint(breakSound, Camera.main.transform.position);
	}

	private void TriggerSparklesVFX()
	{
		GameObject sparkles = Instantiate(blockSparklesVFX, transform.position, transform.rotation);
		Destroy(sparkles,1f);
	}
}
